# -*- coding: utf-8 -*-
"""ML Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIXmaQ1xiAuxp6dxbCjhmbnbaFmi-RkC

# Implement a linear regression model to predict the prices of houses based on their square footage and the number of bedrooms and bathrooms.
"""

# 1. Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 2. Load Data
data=pd.read_csv("/content/real_estate_dataset.csv")
df = pd.DataFrame(data)

# 3. Data Understanding
print("First few rows of the data:")
print(df.head())
print("\nData Information:")
print(df.info())
print("\nSummary Statistics:")
print(df.describe())

# 4. Data Cleaning
# Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# Drop rows with missing values (if any)
df = df.dropna()

# 5. Feature Selection
X = df[['Square_Feet', 'Num_Bedrooms', 'Num_Bathrooms']]
y = df['Price']

# 6. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 7. Model Building
model = LinearRegression()
model.fit(X_train, y_train)

# 8. Model Evaluation
y_pred = model.predict(X_test)
print("\nModel Performance (MSE):", mean_squared_error(y_test, y_pred))

# 9. Prediction Function
def predict_price(square_footage, bedrooms, bathrooms):
    pred = model.predict([[square_footage, bedrooms, bathrooms]])
    return pred[0]

# 10. User Input and Prediction
try:
    print("\n--- House Price Prediction ---")
    sq_ft = float(input("Enter Square Footage: "))
    beds = int(input("Enter number of Bedrooms: "))
    baths = int(input("Enter number of Bathrooms: "))
    price = predict_price(sq_ft, beds, baths)
    print(f"Predicted House Price: ${price:,.2f}")
except Exception as e:
    print("Error in input:", e)

